### PR TITLE
Implemented combobox

### LINKED ISSUE #13: Comboboxes?
I want to use this for the menu of my game, and looking at the libui controlgallery screenshots they have something called a "Combobox". It looks like you havent implemented it yet though. Do you have any plans to do it? If not, id be willing to try and do it myself

EDIT: I tried doing it myself, but after generating the bindings, I had no idea how to use them or how to make a higher level wrapper around them. It would be great if you could add comboboxes yourself, as I cant figure it out

### PR DESCRIPTION
**Pull request by nsgonultas**
Closes #13

### CODE REVIEW

**Comment by joaoventura** [comment]
I haven't ran the code as I'm quite busy now, but I'm assuming everything is right and all the test passes. Thanks for the contribution! 👍

**Comment by nsgonultas** [comment]
You're welcome @joaoventura  :+1: BTW, if you're busy what about adding some people as collabrators so they can push code without taking your time? I would like to see pylibui completed. 

And maybe you can open some more issues about missing implementations and add hacktoberfest labels to these issues. I think this repo is perfect for hacktoberfest.

**Comment by joaoventura** [comment]
I think it is a good idea, as I really like to see pylibui in better shape so it can be usable. 

I have thought on a very simple "metric" to add maintainers: if a person has created at least one or two PRs with the ctypes bindings, pylibui wrapper and test/examples, they clearly understand the idea behind pylibui and can be maintainers. What do you think @nsgonultas? 

And @superzazu could also be added as maintainer by this "metric"..

**Comment by nsgonultas** [comment]
I'm already eager to contribute pylibui, this will be good. And I can write another binding+wrapper+test/examples until next week.

**Pull request merged**
