### PR TITLE
Improved bindings.py

### LINKED ISSUE #40: Update ui.h
The script to generate automatically the bindings parses the libui header file in pylibui/scripts/ui.h. The current header file is 4 months old now, so there is definitely some things that were added to libui in the last months that are not in the pylibui ctype wrapper files. 

We just need to regularly copy ui.h from the libui project, to keep binding generation up-to-date and manually integrate the new functions in the wrapper files. In the future we may try to automatize some things, but let the project mature a little bit more..

### PR DESCRIPTION
**Pull request by nsgonultas**
bindings.py now downloading original ui.h from clibui repository and compares original file with local one. Also I'm updated _ui.h_.

Fixes #40

### CODE REVIEW

**Comment by nsgonultas** [comment]
What about this?

**Comment by joaoventura** [comment]
I suggest to wrap all the instructions to download ui.h in a function, and add a way to execute that function when calling the bindings.py script, eg: "python3 bindings.py download"..

**Comment by nsgonultas** [comment]
The point was that when a contributor tries to generate bindings, it compares with the original, so nobody works with an old ui.h. But I can change it if you want :+1:

**Comment by nsgonultas** [comment]
Changed.

**Comment by nsgonultas** [comment]
All contributors, please don't forget to sync your forks/clones: https://help.github.com/articles/syncing-a-fork/

**Pull request merged**
