### PR TITLE
visibility default value now to false

### PR DESCRIPTION
**Pull request by waghanza**

### CODE REVIEW

**Comment by nsgonultas** [comment]
What is your operating system @waghanza? This change is completely ok for me, because I also get a fail in that test. But as far as I remember this test wasn't failing on macOS, can somebody with macOS check it please?

**Comment by waghanza** [comment]
@nsgonultas I'm on `fedora`

I can probably add testing on `OS X` workers to ensure compatibility

**Comment by nsgonultas** [comment]
https://github.com/joaoventura/pylibui/pull/27#issuecomment-255535558

**Comment by waghanza** [comment]
@nsgonultas it seems to work on `OS X`

https://travis-ci.org/waghanza/pylibui/jobs/185780337

**Comment by joaoventura** [comment]
So, this was merged in #54, can we close this Pull Request?

**Comment by waghanza** [comment]
absolutely

**Pull request closed without merging**
